#!/usr/bin/env node

var fs   = require('fs');
var path = require('path');

var role = process.env.AWS_LAMBDA_IAM_ROLE_ARN;

var file_path = path.resolve(__dirname, '..', 'project.json');
var file_body = JSON.stringify({
    name: 'example',
    description: 'Example project',
    role: role
}, null, '    ');

fs.writeFile(file_path, file_body, function(err) {
    if (err) {
        return console.log(err);
    }
    console.log(file_path + ' was saved.');
});
